### ISSUE TITLE
The redhat.rhel_metrics.elasticsearch role does not set default elasticsearch_metrics_provider

### ISSUE THREAD

**Issue by kurik** [performancecopilot/ansible-pcp#10]
The ```redhat.rhel_metrics.elasticsearch``` role does not set default ```elasticsearch_metrics_provider```.
A reproduction playbook is as follows:

```yaml
# SPDX-License-Identifier: MIT
---
- name: Test import from Elasticsearch
  hosts: all

  roles:
    - role: performancecopilot.metrics.elasticsearch
      vars:
        elasticsearch_agent: yes
```

Output of a run of such playbook:

```
fatal: [10.89.0.6]: FAILED! => {"msg": "The conditional check 'elasticsearch_metrics_provider == 'pcp'' failed. The error was: error while evaluating conditional (elasticsearch_metrics_provider == 'pcp'): 'elasticsearch_metrics_provider' is undefined\n\nThe error appears to be in '/usr/share/ansible/collections/ansible_collections/redhat/rhel_metrics/roles/elasticsearch/tasks/main.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Establish Elasticsearch metrics package names\n  ^ here\n"}

```
