### ISSUE TITLE
The redhat.rhel_metrics.mssql role does not set default mssql_metrics_provider 

### ISSUE THREAD

**Issue by kurik** [performancecopilot/ansible-pcp#11]
The ```redhat.rhel_metrics.mssql``` role does not set default ```mssql_metrics_provider```.
A reproduction playbook is as follows:

```yaml
# SPDX-License-Identifier: MIT
---
- name: Test mssql
  hosts: all

  roles:
    - role: performancecopilot.metrics.mssql
```

Output of a run of such playbook:

```
fatal: [10.89.0.12]: FAILED! => {"msg": "The conditional check 'mssql_metrics_provider == 'pcp'' failed. The error was: error while evaluating conditional (mssql_metrics_provider == 'pcp'): 'mssql_metrics_provider' is undefined\n\nThe error appears to be in '/usr/share/ansible/collections/ansible_collections/redhat/rhel_metrics/roles/mssql/tasks/main.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Establish SQL Server metrics package names\n  ^ here\n"}
```
