### ISSUE TITLE
The spark sub-role does not start pmcd and does not register openmetrics pmda in pmcd

### ISSUE THREAD

**Issue by kurik** [performancecopilot/ansible-pcp#15]
The following playbook does not start ```pcp2spark``` service because ```pmcd```, required by the ```pcp2spark``` service, is not started by the spark sub-role. Also the spark sub-role installs openmetrics pmda, but does not register it in pmcd:

```yaml
# SPDX-License-Identifier: MIT
---
- name: Spark role test
  hosts: all

  roles:
    - role: performancecopilot.metrics.spark
      vars:
        spark_export_metrics: yes
```

When pmcd is started manually on the target host, and the openmetrics pmda is already installed and registered, then the playbook above works just fine.
