### ISSUE TITLE
The redhat.rhel_metrics.bpftrace role does not set default bpftrace_metrics_provider

### ISSUE THREAD

**Issue by kurik** [performancecopilot/ansible-pcp#8]
The ```redhat.rhel_metrics.bpftrace``` role does not set default ```bpftrace_metrics_provider```.
A reproduction playbook is as follows:

```yaml
# SPDX-License-Identifier: MIT
---
- name: Test BPFTrace
  hosts: all

  roles:
    - role: redhat.rhel_metrics.bpftrace
```

Output of a run of such playbook:

```
fatal: [10.89.0.3]: FAILED! => {"msg": "The conditional check 'bpftrace_metrics_provider == 'pcp'' failed. The error was: error while evaluating conditional (bpftrace_metrics_provider == 'pcp'): 'bpftrace_metrics_provider' is undefined
```
